version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27019:27019'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./src
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

volumes:
  mongo-data:
